image: node:22-bookworm
command:
  - "/bin/bash"
  - "-c"
  - "npm config set update-notifier false && npm start --silent"
env:
  NODE_PATH: "./node_modules"
# egress: true
# workDir: "/script"
# scriptDir: "/script"